export {
  computeEndsAt,
  computeSalePrice,
  formatDiscountCountdown,
  formatPriceAmount,
  getDiscountCountdownUnits,
  isValidDiscountDuration,
  resolveDiscountStatus,
  resolveEffectivePrice,
  roundMoney,
  type DiscountCountdownUnits,
  type DiscountDuration,
  type DiscountStatus,
  type DiscountWindowInput,
  type EffectivePriceResult,
} from './lib/game-discount';
