export const typography = {
  fontBody: 'var(--font-body)',
  fontDisplay: 'var(--font-display)',
  fontMono: 'var(--font-mono)',
  weights: {
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
  },
  sizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    base: '1rem',
    md: '1.0625rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.5rem',
    '5xl': '3.5rem',
  },
  lineHeights: {
    none: 1,
    tight: 1.15,
    snug: 1.3,
    normal: 1.5,
    body: 1.65,
    prose: 1.75,
  },
  letterSpacing: {
    tighter: '-0.03em',
    tight: '-0.02em',
    normal: '0',
    wide: '0.04em',
    wider: '0.08em',
  },
} as const;

/** CSS custom properties for the type scale (fonts come from next/font). */
export const typographyCssVars = {
  '--font-size-xs': typography.sizes.xs,
  '--font-size-sm': typography.sizes.sm,
  '--font-size-base': typography.sizes.base,
  '--font-size-md': typography.sizes.md,
  '--font-size-lg': typography.sizes.lg,
  '--font-size-xl': typography.sizes.xl,
  '--font-size-2xl': typography.sizes['2xl'],
  '--font-size-3xl': typography.sizes['3xl'],
  '--font-size-4xl': typography.sizes['4xl'],
  '--font-size-5xl': typography.sizes['5xl'],
  '--line-height-none': String(typography.lineHeights.none),
  '--line-height-tight': String(typography.lineHeights.tight),
  '--line-height-snug': String(typography.lineHeights.snug),
  '--line-height-normal': String(typography.lineHeights.normal),
  '--line-height-body': String(typography.lineHeights.body),
  '--line-height-prose': String(typography.lineHeights.prose),
  '--letter-spacing-tighter': typography.letterSpacing.tighter,
  '--letter-spacing-tight': typography.letterSpacing.tight,
  '--letter-spacing-normal': typography.letterSpacing.normal,
  '--letter-spacing-wide': typography.letterSpacing.wide,
  '--letter-spacing-wider': typography.letterSpacing.wider,
  '--font-weight-light': String(typography.weights.light),
  '--font-weight-normal': String(typography.weights.normal),
  '--font-weight-medium': String(typography.weights.medium),
  '--font-weight-semibold': String(typography.weights.semibold),
  '--font-weight-bold': String(typography.weights.bold),
  '--font-weight-extrabold': String(typography.weights.extrabold),
  '--font-mono':
    "ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
} as const;
