export const clerkAppearance = {
  variables: {
    colorBackground: '#0a0c16',
    colorInputBackground: 'rgba(10, 12, 22, 0.9)',
    colorInputText: '#f3f4f6',
    colorPrimary: '#a855f7',
    colorText: '#f3f4f6',
    colorTextSecondary: '#b8c0cc',
    colorDanger: '#ef4444',
    colorSuccess: '#10b981',
    colorNeutral: '#94a3b8',
    borderRadius: '0.625rem',
    // Inherit the next/font body face from the document (do not hardcode a CDN name).
    fontFamily: 'var(--font-body)',
    fontFamilyButtons: 'var(--font-body)',
  },
  elements: {
    rootBox: 'authClerkRoot',
    cardBox: 'authClerkCardBox',
    card: 'authClerkCard',
    headerTitle: 'authClerkTitle',
    headerSubtitle: 'authClerkSubtitle',
    socialButtonsBlockButton: 'authClerkSocialBtn',
    formButtonPrimary: 'authClerkPrimaryBtn',
    formFieldInput: 'authClerkInput',
    footerActionLink: 'authClerkLink',
    identityPreviewEditButton: 'authClerkLink',
    formFieldAction: 'authClerkLink',
    dividerLine: 'authClerkDivider',
    dividerText: 'authClerkDividerText',
    footer: 'authClerkFooter',
    alert: 'authClerkAlert',
  },
  layout: {
    socialButtonsPlacement: 'bottom',
    showOptionalFields: false,
  },
};
